# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftLearnDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLearnDemo
  #rx
   pod 'RxSwift', '5.1.0'
   pod 'RxCocoa', '5.1.0'
   pod 'RxDataSources', '4.0.1'
  # NetWork
   pod 'Alamofire'

  target 'SwiftLearnDemoTests' do
    inherit! :search_paths
    # Pods for testing
 
  end

  target 'SwiftLearnDemoUITests' do
    # Pods for testing
  end

end
